In [1]:
# importing Library

import numpy as np

There are 6 ways to create arrays in numpy
1. Conversion from other Python structures (i.e. lists and tuples)
2. Intrinsic NumPy array creation functions (e.g. arange, ones, zeros, etc.)
3. Replicating, joining, or mutating existing arrays
4. Reading arrays from disk, either from standard or custom formats
5. Creating arrays from raw bytes through the use of strings or buffers
6. Use of special library functions (e.g., random)

Conversion from other Python structures (i.e. lists and tuples)

In [2]:
a = np.array([1,2,3])   # 1D
b = np.array([[1,2,3], [4,5,6]])   # 2D
c = np.array([[[1,2], [3,4]], [[5,6],[7,8]]])   # 3D
# print(a)
# print(b)
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [3]:
a = np.array((22,33,56), dtype = float)
print(a)

[22. 33. 56.]


Intrinsic NumPy array creation functions (e.g. arange, ones, zeros, etc.)

In [4]:
# arange creates array with regularly incrementing values
a = np.arange(0,11,2)
a

array([ 0,  2,  4,  6,  8, 10])

In [5]:
#reshape changes the dimensions
a = a.reshape((3,2))
print(a)

[[ 0  2]
 [ 4  6]
 [ 8 10]]


In [6]:
np.arange(8).reshape(2,2,2)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [7]:
# ones creates array with ones
a = np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
a = np.ones((3,3), dtype = np.int8)
print(a)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [9]:
a = np.zeros((5,), dtype = np.int16)
a

array([0, 0, 0, 0, 0], dtype=int16)

In [10]:
a = np.random.random((3,3))
a

array([[0.98968976, 0.74939589, 0.63203019],
       [0.39160722, 0.12729663, 0.72691585],
       [0.70125728, 0.21289419, 0.98709261]])

In [11]:
# Creating random array of integers
a = np.random.random((3,3))*100
a = a.astype(np.int32)
a

array([[31, 54, 31],
       [15, 27, 24],
       [21, 89, 38]])

linspace will create arrays with a specified number of elements, and spaced equally between the specified beginning and end values

In [15]:
# This gives 10 values equally spaced from 2 to 20 both included
a = np.linspace(2,20,10)
print(a)

[ 2.  4.  6.  8. 10. 12. 14. 16. 18. 20.]


In [16]:
# CREATING 2D and 3D arrays
a = np.identity(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [21]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [26]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [27]:
np.diag([1,2,3], -1)

array([[0, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0]])

In [28]:
np.diag([1,2,3], 1)

array([[0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3],
       [0, 0, 0, 0]])

In [29]:
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [30]:
np.diag(a)

array([0, 4, 8])

In [31]:
# vander(x, n) defines a Vandermonde matrix as a 2D NumPy array.
# Each column of the Vandermonde matrix is a decreasing power of the input 1D array or list or tuple,
# x where the highest polynomial order is n-1

np.vander([1,2,3,4], 4)


array([[ 1,  1,  1,  1],
       [ 8,  4,  2,  1],
       [27,  9,  3,  1],
       [64, 16,  4,  1]])

In [34]:
np.indices((3,3))

array([[[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]],

       [[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]])

### Array Attributes

In [40]:
a = np.arange(8, dtype = np.int8).reshape(2,2,2)
print(a)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [37]:
a.ndim

3

In [38]:
a.shape

(2, 2, 2)

In [41]:
a.dtype

dtype('int8')

In [42]:
a.size

8

In [43]:
a.itemsize

1

### Changing Data Type

In [47]:
a = a.astype(np.int32)
a

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [48]:
a.dtype

dtype('int32')

In [49]:
a.itemsize

4

In [50]:
a.size

8

### Array Operations

In [52]:
a1 = np.arange(9).reshape(3,3)
a2 = np.arange(9,18).reshape(3,3)

a2

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [ ]:
 # Operations
 # +
 # -
 # *
 # /
 # **

In [58]:
# Scalar operations - Operation on array with a scalar(number).
a1 + 2
# a1 - 1
# a1 * 2
# a1 / 2
# a1 ** 2

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [65]:
# Relational
# ==, !=, >, <, >=, <=
a1 == a2
# a1 != a2
# a1 >= a2
# a1 > a2
# a1 <= a2
# a1 < a2

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [70]:
# vector operations - operations on two vectors
a1 + a2
# a1 * a2
# a1 ** a2

array([[ 9, 11, 13],
       [15, 17, 19],
       [21, 23, 25]])