In [1]:
# importing Library

import numpy as np

There are 6 ways to create arrays in numpy
1. Conversion from other Python structures (i.e. lists and tuples)
2. Intrinsic NumPy array creation functions (e.g. arange, ones, zeros, etc.)
3. Replicating, joining, or mutating existing arrays
4. Reading arrays from disk, either from standard or custom formats
5. Creating arrays from raw bytes through the use of strings or buffers
6. Use of special library functions (e.g., random)

Conversion from other Python structures (i.e. lists and tuples)

In [4]:
a = np.array([1,2,3])   # 1D
b = np.array([[1,2,3], [4,5,6]])   # 2D
c = np.array([[[1,2], [3,4]], [[5,6],[7,8]]])   # 3D
# print(a)
# print(b)
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [6]:
a = np.array((22,33,56), dtype = float)
print(a)

[22. 33. 56.]


Intrinsic NumPy array creation functions (e.g. arange, ones, zeros, etc.)

In [9]:
# arange creates array with regularly incrementing values
a = np.arange(0,11,2)
a

array([ 0,  2,  4,  6,  8, 10])

In [12]:
#reshape changes the dimensions
a = a.reshape((3,2))
print(a)

[[ 0  2]
 [ 4  6]
 [ 8 10]]


In [14]:
np.arange(8).reshape(2,2,2)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [17]:
# ones creates array with ones
a = np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [23]:
a = np.ones((3,3), dtype = np.int8)
print(a)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [28]:
a = np.zeros((5,), dtype = np.int16)
a

array([0, 0, 0, 0, 0], dtype=int16)

In [30]:
a = np.random.random((3,3))
a

array([[0.57849187, 0.77223192, 0.85018043],
       [0.66871329, 0.24011239, 0.97635672],
       [0.37246362, 0.33143244, 0.73873809]])

In [35]:
# Creating random array of integers
a = np.random.random((3,3))*100
a = a.astype(np.int32)
a

array([[72, 16,  8],
       [28, 41, 98],
       [96, 35, 19]])

linspace will create arrays with a specified number of elements, and spaced equally between the specified beginning and end values