In [1]:
# importing Library

import numpy as np

There are 6 ways to create arrays in numpy
1. Conversion from other Python structures (i.e. lists and tuples)
2. Intrinsic NumPy array creation functions (e.g. arange, ones, zeros, etc.)
3. Replicating, joining, or mutating existing arrays
4. Reading arrays from disk, either from standard or custom formats
5. Creating arrays from raw bytes through the use of strings or buffers
6. Use of special library functions (e.g., random)

Conversion from other Python structures (i.e. lists and tuples)

In [2]:
a = np.array([1,2,3])   # 1D
b = np.array([[1,2,3], [4,5,6]])   # 2D
c = np.array([[[1,2], [3,4]], [[5,6],[7,8]]])   # 3D
# print(a)
# print(b)
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [3]:
a = np.array((22,33,56), dtype = float)
print(a)

[22. 33. 56.]


Intrinsic NumPy array creation functions (e.g. arange, ones, zeros, etc.)

In [4]:
# arange creates array with regularly incrementing values
a = np.arange(0,11,2)
a

array([ 0,  2,  4,  6,  8, 10])

In [5]:
#reshape changes the dimensions
a = a.reshape((3,2))
print(a)

[[ 0  2]
 [ 4  6]
 [ 8 10]]


In [6]:
np.arange(8).reshape(2,2,2)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [7]:
# ones creates array with ones
a = np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
a = np.ones((3,3), dtype = np.int8)
print(a)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [9]:
a = np.zeros((5,), dtype = np.int16)
a

array([0, 0, 0, 0, 0], dtype=int16)

In [10]:
a = np.random.random((3,3))
a

array([[0.1509758 , 0.10912513, 0.8045441 ],
       [0.77069155, 0.63613055, 0.66031364],
       [0.94744736, 0.46418219, 0.71185184]])

In [11]:
# Creating random array of integers
a = np.random.random((3,3))*100
a = a.astype(np.int32)
a

array([[49, 95, 76],
       [80, 64, 21],
       [23, 62, 68]])

linspace will create arrays with a specified number of elements, and spaced equally between the specified beginning and end values

In [12]:
# This gives 10 values equally spaced from 2 to 20 both included
a = np.linspace(2,20,10)
print(a)

[ 2.  4.  6.  8. 10. 12. 14. 16. 18. 20.]


In [13]:
# CREATING 2D and 3D arrays
a = np.identity(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [14]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [15]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [16]:
np.diag([1,2,3], -1)

array([[0, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0]])

In [17]:
np.diag([1,2,3], 1)

array([[0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3],
       [0, 0, 0, 0]])

In [18]:
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [19]:
np.diag(a)

array([0, 4, 8])

In [20]:
# vander(x, n) defines a Vandermonde matrix as a 2D NumPy array.
# Each column of the Vandermonde matrix is a decreasing power of the input 1D array or list or tuple,
# x where the highest polynomial order is n-1

np.vander([1,2,3,4], 4)


array([[ 1,  1,  1,  1],
       [ 8,  4,  2,  1],
       [27,  9,  3,  1],
       [64, 16,  4,  1]])

In [21]:
np.indices((3,3))

array([[[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]],

       [[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]])

### Array Attributes

In [22]:
a = np.arange(8, dtype = np.int8).reshape(2,2,2)
print(a)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [23]:
a.ndim

3

In [24]:
a.shape

(2, 2, 2)

In [25]:
a.dtype

dtype('int8')

In [26]:
a.size

8

In [27]:
a.itemsize

1

### Changing Data Type

In [28]:
a = a.astype(np.int32)
a

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [29]:
a.dtype

dtype('int32')

In [30]:
a.itemsize

4

In [31]:
a.size

8

### Array Operations

In [32]:
a1 = np.arange(9).reshape(3,3)
a2 = np.arange(9,18).reshape(3,3)

a2

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [33]:
 # Operations
 # +
 # -
 # *
 # /
 # **

In [34]:
# Scalar operations - Operation on array with a scalar(number).
a1 + 2
# a1 - 1
# a1 * 2
# a1 / 2
# a1 ** 2

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [35]:
# Relational
# ==, !=, >, <, >=, <=
a1 == a2
# a1 != a2
# a1 >= a2
# a1 > a2
# a1 <= a2
# a1 < a2

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [36]:
# vector operations - operations on two vectors
a1 + a2
# a1 * a2
# a1 ** a2

array([[ 9, 11, 13],
       [15, 17, 19],
       [21, 23, 25]])

### Array Functions

In [37]:
a = np.random.random((3,3))
a = np.round(a*100, 2)
a

array([[80.89, 56.61, 78.68],
       [64.41, 22.33, 30.46],
       [21.91, 86.33, 19.41]])

In [38]:
a = np.round(a)
a = a.astype(np.int32)
a

array([[81, 57, 79],
       [64, 22, 30],
       [22, 86, 19]])

In [39]:
# min/max/sum/prod
# 0 -> col , 1 -> row
np.min(a, axis = 0)
# np.max(a, axis = 0)
# np.sum(a, axis = 1)
# np.prod(a, axis = 1)

array([22, 22, 19])

In [40]:
# mean, median, std, var
np.mean(a, axis = 0)
np. median(a, axis = 1)

array([79., 30., 22.])

In [41]:
# Trignometric Functions - sin, cos, tan, cot, etc..
np.sin(a)
# np.cos([0,30,45,60,90])

array([[-0.62988799,  0.43616476, -0.44411267],
       [ 0.92002604, -0.00885131, -0.98803162],
       [-0.00885131, -0.92345845,  0.14987721]])

In [42]:
# dot product or matrix multiplication
a1 = np.arange(6).reshape(2,3)
a2 = np.arange(6,12).reshape(3,2)

print(a1)
print()
print(a2)

[[0 1 2]
 [3 4 5]]

[[ 6  7]
 [ 8  9]
 [10 11]]


In [43]:
np.dot(a1, a2)

array([[ 28,  31],
       [100, 112]])

In [44]:
# log , exp
np.log(a1)

C:\Users\Kishor Reddy\AppData\Local\Temp\ipykernel_5360\2688507398.py:2: RuntimeWarning: divide by zero encountered in log
  np.log(a1)


array([[      -inf, 0.        , 0.69314718],
       [1.09861229, 1.38629436, 1.60943791]])

In [45]:
a1 = np.exp(a1)
a1

array([[  1.        ,   2.71828183,   7.3890561 ],
       [ 20.08553692,  54.59815003, 148.4131591 ]])

In [46]:
# round/ floor/ ceil
np.floor(a1)

array([[  1.,   2.,   7.],
       [ 20.,  54., 148.]])

### Indexing and Slicing

In [47]:
# default_rng is seed value gives same random values for again when executed
a1 = (np.random.default_rng(42).random((8))*100).astype(np.int32)
a2 = (np.random.default_rng(42).random((2,4))*100).astype(np.int32)
a3 = (np.random.default_rng(42).random((2,2,2))*100).astype(np.int32)
print(a1)
print("Array 2")
print(a2)
print("Array 3")
print(a3)

[77 43 85 69  9 97 76 78]
Array 2
[[77 43 85 69]
 [ 9 97 76 78]]
Array 3
[[[77 43]
  [85 69]]

 [[ 9 97]
  [76 78]]]


In [48]:
# accessing single value in all 3 dimensions 97
a1[5]
a2[1][1]
a3[1][0][1]

97

In [49]:
a2[0]

array([77, 43, 85, 69])

In [50]:
a3[1]

array([[ 9, 97],
       [76, 78]])

In [51]:
# slicing - array[start:end+1:step]
a1[2:6:2]

array([85,  9])

In [52]:
print(a1)
a1[-2:-5:-1]

[77 43 85 69  9 97 76 78]


array([76, 97,  9])

In [53]:
print(a1)
a1[-4:-1]

[77 43 85 69  9 97 76 78]


array([ 9, 97, 76])

In [54]:
print(a2)
a2[:, 1:3]

[[77 43 85 69]
 [ 9 97 76 78]]


array([[43, 85],
       [97, 76]])

In [55]:
print(a3)
a3[1,:,:]

[[[77 43]
  [85 69]]

 [[ 9 97]
  [76 78]]]


array([[ 9, 97],
       [76, 78]])

In [56]:
a2 = np.arange(25).reshape(5,5)
a2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [57]:
a2[1::2,1::2]

array([[ 6,  8],
       [16, 18]])

In [58]:
a2[1:4,1:4]

array([[ 6,  7,  8],
       [11, 12, 13],
       [16, 17, 18]])

In [59]:
a3 = np.arange(48).reshape(3,4,4)
a3

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]]])

In [60]:
a3[::2,1::2,:]

array([[[ 4,  5,  6,  7],
        [12, 13, 14, 15]],

       [[36, 37, 38, 39],
        [44, 45, 46, 47]]])

### Iterating

In [61]:
a1

array([77, 43, 85, 69,  9, 97, 76, 78])

In [62]:
for i in a1:
    print(i)

77
43
85
69
9
97
76
78


In [63]:
a2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [64]:
for i in a2:
    print(i)

[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]
[15 16 17 18 19]
[20 21 22 23 24]


In [65]:
type(a2)

numpy.ndarray

In [66]:
a3

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]]])

In [67]:
for i in a3:
    print(i)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
[[32 33 34 35]
 [36 37 38 39]
 [40 41 42 43]
 [44 45 46 47]]


In [68]:
for i in np.nditer(a2):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24


### Reshaping

In [69]:
# transpose
print(a2)
# np.transpose(a2)
a2.T

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


array([[ 0,  5, 10, 15, 20],
       [ 1,  6, 11, 16, 21],
       [ 2,  7, 12, 17, 22],
       [ 3,  8, 13, 18, 23],
       [ 4,  9, 14, 19, 24]])

In [70]:
# ravel - gives a 1D array of nD array
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

### Stacking

In [71]:
a1 = np.arange(4).reshape(2,2)
a2 = np.arange(4,8).reshape(2,2)
print(f"{a1} \n\n\n a2\n{a2}")

[[0 1]
 [2 3]] 


 a2
[[4 5]
 [6 7]]


In [72]:
# hstack - horizontal stack
np.hstack((a1,a2))


array([[0, 1, 4, 5],
       [2, 3, 6, 7]])

In [73]:
# vertical stack - vstack
np.vstack((a1,a2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

### Splitting

In [74]:
temp = a1
a1 = np.hstack((a1,a2))
a2 = np.vstack((temp, a2))
print(a1)
print()
print(a2)

[[0 1 4 5]
 [2 3 6 7]]

[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [75]:
np.hsplit(a1,2)

[array([[0, 1],
        [2, 3]]),
 array([[4, 5],
        [6, 7]])]

In [76]:
np.vsplit(a2, 2)

[array([[0, 1],
        [2, 3]]),
 array([[4, 5],
        [6, 7]])]

In [77]:
print(a1)
np.split(a1, 4, axis = 1)

[[0 1 4 5]
 [2 3 6 7]]


[array([[0],
        [2]]),
 array([[1],
        [3]]),
 array([[4],
        [6]]),
 array([[5],
        [7]])]

### Advanced Indexing

In [78]:
a = np.arange(30).reshape(6,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [79]:
a[1::2, ::2]

array([[ 5,  7,  9],
       [15, 17, 19],
       [25, 27, 29]])

In [80]:
# Fancy Indexing
a[::2, [1,2,4]]

array([[ 1,  2,  4],
       [11, 12, 14],
       [21, 22, 24]])

In [81]:
a[[0,1,5], :]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [25, 26, 27, 28, 29]])

In [82]:
a[[1,2,5],[0,1,4]]

array([ 5, 11, 29])

In [83]:
# Boolean Indexing
a = np.random.randint(1,100,20).reshape(4,5)
a

array([[24, 88,  6, 99, 28],
       [29,  8, 77, 44, 75],
       [58, 30, 49, 62, 69],
       [24, 90, 42, 59, 61]])

In [84]:
a[a > 50]

array([88, 99, 77, 75, 58, 62, 69, 90, 59, 61])

In [85]:
a[a%2 == 0]

array([24, 88,  6, 28,  8, 44, 58, 30, 62, 24, 90, 42])

In [86]:
a[(a > 50) & (a % 2 == 0)]

array([88, 58, 62, 90])

In [87]:
a[~(a % 2 == 0)]

array([99, 29, 77, 75, 49, 69, 59, 61])

### Broadcasting

It is the behaviour of numpy when a operation is done between 2 different dimension arrays

In [88]:
# same shape and dimension
a1 = np.random.randint(1,100,(2,3))
a2 = np.random.randint(1,100,(2,3))
print(a1+a2)

[[ 61  59  63]
 [ 64  42 121]]


In [91]:
# different dimension 2d with 1d
a1 = np.arange(9).reshape(3,3)    #2D
a2 = np.arange(3).reshape(1,3)   #1D
print(a1.__repr__())
print(a2.__repr__())

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])
array([[0, 1, 2]])


In [92]:
print(a1+a2)

[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]]


## Rules
1. Make the two arrays have the same number of dimensions.If the numbers of dimensions of the two arrays are different, add new dimensions with size 1 to the head of the array with the smaller dimension.
2. . Make each dimension of the two arrays the same size
.

If the sizes of each dimension of the two arrays do not match, dimensions with size 1 are stretched to the size of the other arr
ay.
If there is a dimension whose size is not 1 in either of the two arrays, it cannot be broadcasted, and an error is raised.

In [105]:
a = np.arange(12).reshape(3,4)
b = np.arange(3).reshape(3,1)
print(a.__repr__())
print(b.__repr__())
print(a+b)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])
array([[0],
       [1],
       [2]])
[[ 0  1  2  3]
 [ 5  6  7  8]
 [10 11 12 13]]


In [106]:
a = np.arange(12).reshape(3,4)
b = np.arange(4).reshape(4,)
print(a.__repr__())
print(b.__repr__())
print(a+b)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])
array([0, 1, 2, 3])
[[ 0  2  4  6]
 [ 4  6  8 10]
 [ 8 10 12 14]]


In [107]:
a = np.arange(3).reshape(1,3)
b = np.arange(3).reshape(3,1)
print(a.__repr__())
print(b.__repr__())
print(a+b)

array([[0, 1, 2]])
array([[0],
       [1],
       [2]])
[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [108]:
# broadcasting not possible
a = np.arange(4).reshape(2,2)
b = np.arange(9).reshape(3,3)
print(a.__repr__())
print(b.__repr__())
print(a+b)

array([[0, 1],
       [2, 3]])
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])


ValueError: operands could not be broadcast together with shapes (2,2) (3,3) 

In [110]:
# broadcasting not possible
a = np.arange(4).reshape(2,2)
b = np.arange(16).reshape(4,4)
print(a.__repr__())
print(b.__repr__())
print(a+b)

array([[0, 1],
       [2, 3]])
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])


ValueError: operands could not be broadcast together with shapes (2,2) (4,4) 

### Working With Mathematical Functions

1. sigmoid
2. mean square error
3. binary cross entropy

In [111]:
# sigmoid -> s(x) = 1 / (1 + e power -x)
def sigmoid(array):
    return 1 / (1 + np.exp(-array))

a = np.arange(10)
sigmoid(a)

array([0.5       , 0.73105858, 0.88079708, 0.95257413, 0.98201379,
       0.99330715, 0.99752738, 0.99908895, 0.99966465, 0.99987661])

In [112]:
# Mean Square Error -> mse = 1/n sigma from n = 1 to n (actual(x) - predicted(x)** 2)
def mse(actual, predicted):
    return np.mean((actual - predicted)**2)

actual = np.random.randint(1,50,10)
predicted = np.random.randint(1,50,10)
mse(actual, predicted)

96.1

### Working With Missing Values

In [117]:
a = np.array([1,2,3,np.nan,5,6,np.nan])
a

array([ 1.,  2.,  3., nan,  5.,  6., nan])

In [121]:
np.isnan(a)

array([False, False, False,  True, False, False,  True])

In [122]:
a[~(np.isnan(a))]

array([1., 2., 3., 5., 6.])

In [126]:
a = np.arange(9).reshape(3,3)
b = np.arange(9,18).reshape(3,3)
print(a.__repr__())
print(b.__repr__())
np.meshgrid(a,b)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])
array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])


[array([[0, 1, 2, 3, 4, 5, 6, 7, 8],
        [0, 1, 2, 3, 4, 5, 6, 7, 8],
        [0, 1, 2, 3, 4, 5, 6, 7, 8],
        [0, 1, 2, 3, 4, 5, 6, 7, 8],
        [0, 1, 2, 3, 4, 5, 6, 7, 8],
        [0, 1, 2, 3, 4, 5, 6, 7, 8],
        [0, 1, 2, 3, 4, 5, 6, 7, 8],
        [0, 1, 2, 3, 4, 5, 6, 7, 8],
        [0, 1, 2, 3, 4, 5, 6, 7, 8]]),
 array([[ 9,  9,  9,  9,  9,  9,  9,  9,  9],
        [10, 10, 10, 10, 10, 10, 10, 10, 10],
        [11, 11, 11, 11, 11, 11, 11, 11, 11],
        [12, 12, 12, 12, 12, 12, 12, 12, 12],
        [13, 13, 13, 13, 13, 13, 13, 13, 13],
        [14, 14, 14, 14, 14, 14, 14, 14, 14],
        [15, 15, 15, 15, 15, 15, 15, 15, 15],
        [16, 16, 16, 16, 16, 16, 16, 16, 16],
        [17, 17, 17, 17, 17, 17, 17, 17, 17]])]

### Important functions

1. sort
2. append
3. concatenate
4. unique
5. expand_dims
6. where
7. argmax, argmin
8. cumsum, cumprod
9. percentile
10. histogram
11. corrcoef - correlation coefficients
12. isin
13. flip
14. put
15. delete
16. clip
17. count_nonzero
18. repeat
19. swapaxes
### Set Functions
1. union1d
2. intersect1d
3. setdiff1d
4. setxor1d
5. in1d

