In [1]:
# importing Library

import numpy as np

There are 6 ways to create arrays in numpy
1. Conversion from other Python structures (i.e. lists and tuples)
2. Intrinsic NumPy array creation functions (e.g. arange, ones, zeros, etc.)
3. Replicating, joining, or mutating existing arrays
4. Reading arrays from disk, either from standard or custom formats
5. Creating arrays from raw bytes through the use of strings or buffers
6. Use of special library functions (e.g., random)

Conversion from other Python structures (i.e. lists and tuples)

In [2]:
a = np.array([1,2,3])   # 1D
b = np.array([[1,2,3], [4,5,6]])   # 2D
c = np.array([[[1,2], [3,4]], [[5,6],[7,8]]])   # 3D
# print(a)
# print(b)
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [3]:
a = np.array((22,33,56), dtype = float)
print(a)

[22. 33. 56.]


Intrinsic NumPy array creation functions (e.g. arange, ones, zeros, etc.)

In [4]:
# arange creates array with regularly incrementing values
a = np.arange(0,11,2)
a

array([ 0,  2,  4,  6,  8, 10])

In [5]:
#reshape changes the dimensions
a = a.reshape((3,2))
print(a)

[[ 0  2]
 [ 4  6]
 [ 8 10]]


In [6]:
np.arange(8).reshape(2,2,2)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [7]:
# ones creates array with ones
a = np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
a = np.ones((3,3), dtype = np.int8)
print(a)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [9]:
a = np.zeros((5,), dtype = np.int16)
a

array([0, 0, 0, 0, 0], dtype=int16)

In [10]:
a = np.random.random((3,3))
a

array([[0.98968976, 0.74939589, 0.63203019],
       [0.39160722, 0.12729663, 0.72691585],
       [0.70125728, 0.21289419, 0.98709261]])

In [11]:
# Creating random array of integers
a = np.random.random((3,3))*100
a = a.astype(np.int32)
a

array([[31, 54, 31],
       [15, 27, 24],
       [21, 89, 38]])

linspace will create arrays with a specified number of elements, and spaced equally between the specified beginning and end values

In [15]:
# This gives 10 values equally spaced from 2 to 20 both included
a = np.linspace(2,20,10)
print(a)

[ 2.  4.  6.  8. 10. 12. 14. 16. 18. 20.]


In [16]:
# CREATING 2D and 3D arrays
a = np.identity(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [21]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [26]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [27]:
np.diag([1,2,3], -1)

array([[0, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0]])

In [28]:
np.diag([1,2,3], 1)

array([[0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3],
       [0, 0, 0, 0]])

In [29]:
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [30]:
np.diag(a)

array([0, 4, 8])

In [31]:
# vander(x, n) defines a Vandermonde matrix as a 2D NumPy array.
# Each column of the Vandermonde matrix is a decreasing power of the input 1D array or list or tuple,
# x where the highest polynomial order is n-1

np.vander([1,2,3,4], 4)


array([[ 1,  1,  1,  1],
       [ 8,  4,  2,  1],
       [27,  9,  3,  1],
       [64, 16,  4,  1]])

In [34]:
np.indices((3,3))

array([[[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]],

       [[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]])

### Array Attributes

In [40]:
a = np.arange(8, dtype = np.int8).reshape(2,2,2)
print(a)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [37]:
a.ndim

3

In [38]:
a.shape

(2, 2, 2)

In [41]:
a.dtype

dtype('int8')

In [42]:
a.size

8

In [43]:
a.itemsize

1

### Changing Data Type

In [47]:
a = a.astype(np.int32)
a

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [48]:
a.dtype

dtype('int32')

In [49]:
a.itemsize

4

In [50]:
a.size

8

### Array Operations

In [52]:
a1 = np.arange(9).reshape(3,3)
a2 = np.arange(9,18).reshape(3,3)

a2

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [ ]:
 # Operations
 # +
 # -
 # *
 # /
 # **

In [58]:
# Scalar operations - Operation on array with a scalar(number).
a1 + 2
# a1 - 1
# a1 * 2
# a1 / 2
# a1 ** 2

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [65]:
# Relational
# ==, !=, >, <, >=, <=
a1 == a2
# a1 != a2
# a1 >= a2
# a1 > a2
# a1 <= a2
# a1 < a2

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [70]:
# vector operations - operations on two vectors
a1 + a2
# a1 * a2
# a1 ** a2

array([[ 9, 11, 13],
       [15, 17, 19],
       [21, 23, 25]])

### Array Functions

In [74]:
a = np.random.random((3,3))
a = np.round(a*100, 2)
a

array([[10.41, 37.01, 82.15],
       [82.31, 28.65, 13.33],
       [58.76, 28.72, 26.99]])

In [76]:
a = np.round(a)
a = a.astype(np.int32)
a

array([[10, 37, 82],
       [82, 29, 13],
       [59, 29, 27]])

In [81]:
# min/max/sum/prod
# 0 -> col , 1 -> row
np.min(a, axis = 0)
# np.max(a, axis = 0)
# np.sum(a, axis = 1)
# np.prod(a, axis = 1)

array([10, 29, 13])

In [83]:
# mean, median, std, var
np.mean(a, axis = 0)
np. median(a, axis = 1)

array([37., 29., 29.])

In [85]:
# Trignometric Functions - sin, cos, tan, cot, etc..
np.sin(a)
# np.cos([0,30,45,60,90])

array([ 1.        ,  0.15425145,  0.52532199, -0.95241298, -0.44807362])

In [98]:
# dot product or matrix multiplication
a1 = np.arange(6).reshape(2,3)
a2 = np.arange(6,12).reshape(3,2)

print(a1)
print()
print(a2)

[[0 1 2]
 [3 4 5]]

[[ 6  7]
 [ 8  9]
 [10 11]]


In [88]:
np.dot(a1, a2)

array([[ 28,  31],
       [100, 112]])

In [90]:
# log , exp
np.log(a1)

C:\Users\Kishor Reddy\AppData\Local\Temp\ipykernel_13416\2688507398.py:2: RuntimeWarning: divide by zero encountered in log
  np.log(a1)


array([[      -inf, 0.        , 0.69314718],
       [1.09861229, 1.38629436, 1.60943791]])

In [99]:
a1 = np.exp(a1)
a1

array([[  1.        ,   2.71828183,   7.3890561 ],
       [ 20.08553692,  54.59815003, 148.4131591 ]])

In [100]:
# round/ floor/ ceil
np.floor(a1)

array([[  1.,   2.,   7.],
       [ 20.,  54., 148.]])

### Indexing and Slicing

In [111]:
# default_rng is seed value gives same random values for again when executed
a1 = (np.random.default_rng(42).random((8))*100).astype(np.int32)
a2 = (np.random.default_rng(42).random((2,4))*100).astype(np.int32)
a3 = (np.random.default_rng(42).random((2,2,2))*100).astype(np.int32)
print(a1)
print("Array 2")
print(a2)
print("Array 3")
print(a3)

[77 43 85 69  9 97 76 78]
Array 2
[[77 43 85 69]
 [ 9 97 76 78]]
Array 3
[[[77 43]
  [85 69]]

 [[ 9 97]
  [76 78]]]


In [115]:
# accessing single value in all 3 dimensions 97
a1[5]
a2[1][1]
a3[1][0][1]

97

In [116]:
a2[0]

array([77, 43, 85, 69])

In [117]:
a3[1]

array([[ 9, 97],
       [76, 78]])

In [119]:
# slicing - array[start:end+1:step]
a1[2:6:2]

array([85,  9])

In [122]:
print(a1)
a1[-2:-5:-1]

[77 43 85 69  9 97 76 78]


array([76, 97,  9])

In [124]:
print(a1)
a1[-4:-1]

[77 43 85 69  9 97 76 78]


array([ 9, 97, 76])

In [128]:
print(a2)
a2[:, 1:3]

[[77 43 85 69]
 [ 9 97 76 78]]


array([[43, 85],
       [97, 76]])

In [130]:
print(a3)
a3[1,:,:]

[[[77 43]
  [85 69]]

 [[ 9 97]
  [76 78]]]


array([[ 9, 97],
       [76, 78]])

In [132]:
a2 = np.arange(25).reshape(5,5)
a2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [134]:
a2[1::2,1::2]

array([[ 6,  8],
       [16, 18]])

In [135]:
a2[1:4,1:4]

array([[ 6,  7,  8],
       [11, 12, 13],
       [16, 17, 18]])

In [137]:
a3 = np.arange(48).reshape(3,4,4)
a3

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]]])

In [138]:
a3[::2,1::2,:]

array([[[ 4,  5,  6,  7],
        [12, 13, 14, 15]],

       [[36, 37, 38, 39],
        [44, 45, 46, 47]]])

### Iterating

In [139]:
a1

array([77, 43, 85, 69,  9, 97, 76, 78])

In [140]:
for i in a1:
    print(i)

77
43
85
69
9
97
76
78


In [141]:
a2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [142]:
for i in a2:
    print(i)

[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]
[15 16 17 18 19]
[20 21 22 23 24]


In [143]:
type(a2)

numpy.ndarray

In [144]:
a3

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]]])

In [145]:
for i in a3:
    print(i)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
[[32 33 34 35]
 [36 37 38 39]
 [40 41 42 43]
 [44 45 46 47]]


In [146]:
for i in np.nditer(a2):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24


### Reshaping

In [151]:
# transpose
print(a2)
# np.transpose(a2)
a2.T

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


array([[ 0,  5, 10, 15, 20],
       [ 1,  6, 11, 16, 21],
       [ 2,  7, 12, 17, 22],
       [ 3,  8, 13, 18, 23],
       [ 4,  9, 14, 19, 24]])

In [154]:
# ravel - gives a 1D array of nD array
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

### Stacking

In [172]:
a1 = np.arange(4).reshape(2,2)
a2 = np.arange(4,8).reshape(2,2)
print(f"{a1} \n\n\n a2\n{a2}")

[[0 1]
 [2 3]] 


 a2
[[4 5]
 [6 7]]


In [173]:
# hstack - horizontal stack
np.hstack((a1,a2))


array([[0, 1, 4, 5],
       [2, 3, 6, 7]])

In [174]:
# vertical stack - vstack
np.vstack((a1,a2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

### Splitting

In [176]:
temp = a1
a1 = np.hstack((a1,a2))
a2 = np.vstack((temp, a2))
print(a1)
print()
print(a2)

[[0 1 4 5]
 [2 3 6 7]]

[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [177]:
np.hsplit(a1,2)

[array([[0, 1],
        [2, 3]]),
 array([[4, 5],
        [6, 7]])]

In [178]:
np.vsplit(a2, 2)

[array([[0, 1],
        [2, 3]]),
 array([[4, 5],
        [6, 7]])]

In [185]:
print(a1)
np.split(a1, 4, axis = 1)

[[0 1 4 5]
 [2 3 6 7]]


[array([[0],
        [2]]),
 array([[1],
        [3]]),
 array([[4],
        [6]]),
 array([[5],
        [7]])]

### Advanced Indexing

In [186]:
a = np.arange(30).reshape(6,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [188]:
a[1::2, ::2]

array([[ 5,  7,  9],
       [15, 17, 19],
       [25, 27, 29]])

In [189]:
# Fancy Indexing
a[::2, [1,2,4]]

array([[ 1,  2,  4],
       [11, 12, 14],
       [21, 22, 24]])

In [190]:
a[[0,1,5], :]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [25, 26, 27, 28, 29]])

In [194]:
a[[1,2,5],[0,1,4]]

array([ 5, 11, 29])

In [199]:
# Boolean Indexing
a = np.random.randint(1,100,20).reshape(4,5)
a

array([[92, 93, 31, 31, 31],
       [54, 72, 47,  8,  1],
       [84,  7,  7,  4, 21],
       [49,  3, 16, 17, 96]])

In [200]:
a[a > 50]

array([92, 93, 54, 72, 84, 96])

In [201]:
a[a%2 == 0]

array([92, 54, 72,  8, 84,  4, 16, 96])

In [206]:
a[(a > 50) & (a % 2 == 0)]

array([92, 54, 72, 84, 96])

In [208]:
a[~(a % 2 == 0)]

array([93, 31, 31, 31, 47,  1,  7,  7, 21, 49,  3, 17])